### ISSUE TITLE
掃到很多毒

### ISSUE THREAD

**Issue by twlinxi** [elliot-bia/msg_reply#1]
https://www.virustotal.com/gui/file/5676051ddf3f4dd5337a7c4f39438385d4c4234d2635671c22b3346223d2e556/detection

**Comment by twlinxi** [comment]
> 
> 
> https://www.virustotal.com/gui/file/5676051ddf3f4dd5337a7c4f39438385d4c4234d2635671c22b3346223d2e556/detection

**Comment by Adam-Zhong** [comment]
是的, 会报毒, 引用原作者的话就是因为使用易语言封装导致
但是源码未开源, 所以使用与否取决于自己
另外 ,稳定性不是很好, 已弃坑
